// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPWNY_EoczbX8jESLhekJpKFqhm1xHGuk',
    appId: '1:964608754343:web:be478e70761e1773431182',
    messagingSenderId: '964608754343',
    projectId: 'car-rental-7449',
    authDomain: 'car-rental-7449.firebaseapp.com',
    storageBucket: 'car-rental-7449.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxiIuWb_sgT1s1bKGNS5HnaB4-X960c4',
    appId: '1:964608754343:android:5eb3ab7b397a290e431182',
    messagingSenderId: '964608754343',
    projectId: 'car-rental-7449',
    storageBucket: 'car-rental-7449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyrwPGOzdePPeouX1UyYJWLI388rDes-I',
    appId: '1:964608754343:ios:e54ed71fd4c4d7d6431182',
    messagingSenderId: '964608754343',
    projectId: 'car-rental-7449',
    storageBucket: 'car-rental-7449.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyrwPGOzdePPeouX1UyYJWLI388rDes-I',
    appId: '1:964608754343:ios:ee8677db2f16c685431182',
    messagingSenderId: '964608754343',
    projectId: 'car-rental-7449',
    storageBucket: 'car-rental-7449.firebasestorage.app',
    iosBundleId: 'com.example.carRentalApp.RunnerTests',
  );
}
